# Bugster Configuration File
# This file contains your project configuration and test execution preferences.
# Important: Commit this file to your repository for CI/CD integration to work properly.

# Project Information
project_name: loprogramamos-2
project_id: loprogramamos-2-1755131662
base_url: "http://localhost:3000"

# Project Authentication
credentials:
  - id: admin
    username: admin@admin.com
    password: admin

# Vercel Configuration
# You can create the Vercel Protection Bypass Secret for Automation in this link:
# https://vercel.com/d?to=/[team]/[project]/settings/deployment-protection&title=Deployment+Protection+settings
# x-vercel-protection-bypass: your-bypass-secret


# Test Execution Preferences
# Uncomment and modify the options below to customize test execution behavior.
# CLI options will override these settings when specified.
# preferences:
#   tests:
#     always_run:
#       - .bugster/tests/test1.yaml
#       - .bugster/tests/test2.yaml
#     limit: 5                    # Maximum number of tests to run
#     headless: false             # Run tests in headless mode
#     silent: false               # Run tests in silent mode
#     verbose: false              # Enable verbose output
#     only_affected: false        # Only run tests for affected files
#     parallel: 5                 # Maximum number of concurrent tests
#     output: bugster_output.json # Save test results to JSON file
